INSERT INTO departments (id, title, slug, description) VALUES ( 1,'Hagfræðideild', 'hagfraedideild', 'Menntun í Hagfræðideild er greiðasta leiðin til þátttöku, rannsókna og skilnings á hagkerfi okkar. Kennslan stendur á sterkum grunni og er markmið námsins að veita nemendum góðan undirbúning í hagfræði, stærðfræði og tölfræði og möguleika á sérhæfingu í öðrum greinum.');
INSERT INTO departments (id, title, slug, description) VALUES ( 2,'Iðnaðarverkfræði-, vélaverkfræði- og tölvunarfræðideild', 'ivt', 'Deildin býður upp á fjölbreytt námsframboð verkfræði- og tölvunarfræðigreina. Þessar greinar eiga það sameiginlegt að vera afar hagnýtar og þýðingarmiklar við uppbyggingu og rekstur nútíma þjóðfélaga.');
INSERT INTO departments (id, title, slug, description) VALUES ( 3, 'Íslensku og menningardeild', 'islenska', 'Íslensku- og menningardeild er ein fjögurra deilda á Hugvísindasviði og er ein sú fjölmennasta innan Háskólans. Í deildinni eru nú kenndar milli 10 og 20 greinar, sumar bæði á grunn- og framhaldsstigi, en sumar eingöngu í grunnnámi og aðrar eingöngu í framhaldsnámi.');
INSERT INTO departments (id, title, slug, description) VALUES ( 4, 'Læknadeild', 'laeknadeild', 'Læknadeild annast kennslu og rannsóknir í geislafræði, heilbrigðisgagnafræði, lífeindafræði, læknisfræði og sjúkraþjálfunarfræði. Deildin starfar í nánu samstarfi við Landspítala og fleiri heilbrigðisstofnanir innanlands og utan. Læknadeild er leiðandi í kennslu og rannsóknum í heilbrigðisvísindum hér á landi.');
INSERT INTO departments (id, title, slug, description) VALUES ( 5, 'Sálfræðideild', 'salfraedideild', 'Sálfræði er vísindagrein um huga, heila og hátterni. Grundvöllur sálfræðinnar er fjölbreytilegt rannsóknastarf en greinin er víða hagnýtt, meðal annars í skólum, meðferðarstarfi og atvinnulífi.');
INSERT INTO departments (id, title, slug, description) VALUES ( 6, 'Viðskiptafræði', 'vidskiptafraedi', 'Viðskiptafræðideild hefur gegnt forystuhlutverki í menntun stjórnenda og sérfræðinga á sviði viðskiptafræði í áratugi. Deildin hefur lagt metnað sinn í að miðla alþjóðlega viðurkenndri þekkingu með því að vera leiðandi í rannsóknum, kennslu og þjónustu við íslenskt atvinnulíf.');


INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('HAG403G', 'Þættir í eindahagfræði (Þættir í rekstrarhagfræði)', 6, 'Vor', 'Grunnám', 'https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=04530620230&kennsluar=2022', 1);
INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('HAG104M', 'Hagnýttar hagmælingar', 6, 'Haust', 'Grunnám/Framhaldsnám','https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=70754420226&kennsluar=2022',1 );

INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('TÖL403G', 'Greining reiknirita', 6, 'Vor', 'Grunnám', 'https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=08716220230&kennsluar=2022', 2);
INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('HBV101G', 'Inngangur að hugbúnaðarverkfræði',4, 'Haust', 'Grunnám','https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=71152220226&kennsluar=2022', 2 );
INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('TÁK502G', 'Táknmálstúlkun I', 20, 'Haust', 'Grunnám', 'https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=05102020226&kennsluar=2022', 3);
INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('AMV105G', '	Mál annarrar ættar I: tyrkneska', 10, 'Haust', 'Grunnám', 'https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=70852020226&kennsluar=2022', 3);
INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('HGF003G	', 'Verkleg þjálfun - val', 8, 'Vor', 'Grunnám', 'https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=71075420230&kennsluar=2022', 4);
INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('LÆK514F', 'Heimilislæknisfræði', 9, 'Haust', 'Framhaldsnám', 'https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=71118020226&kennsluar=2022', 4);
INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('SÁL239F', '	Líkön fyrir undirliggjandi breytur II', 8, 'Vor', 'Framhaldsnám', 'https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=70893820230&kennsluar=2022', 5);
INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('SÁL244F', 'Hegðunar- og námsfræði', 10, 'Vor', 'Framhaldsnám', 'https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=71043620230&kennsluar=2022', 5);
INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('VST101L', 'MS ritgerð', 30, 'Sumar', 'Framhaldsnám', 'https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=91065620233&kennsluar=2022', 6);
INSERT INTO courses (number, title, units, semester, level, url,  departments) VALUES ('MBA310F', 'Samkeppnishæfni og virðissköpun', 6, 'Haust', 'Framhaldsnám', 'https://ugla.hi.is/kennsluskra/?tab=nam&chapter=namskeid&id=71164020226&kennsluar=2022',6);

